language: node_js
node_js:
    - "0.10"

branches:
    only:
        - master
        - dev

install:
    - npm install -g grunt-cli
    - npm install

script:
    - grunt urequire:dev
    - grunt testci